# ------------------------------------------------
# Camerons Ansible PlayBook 4
#
# Purpose:  Test conditions in ansible only on windows 
# ------------------------------------------------
- name: Cam's playbook 4
  hosts: all
  gather_facts: true
  # Variables - lines to add to hosts file
  vars:
    hostspath: 'c:\Windows\System32\Drivers\etc\hosts'
    dontexist: 'c:\Door\System32\help.txt'
    lines:
    - 192.0.1.99 foo.cam.net
    - 192.0.1.100 foo.cam.net
    - 192.0.1.101 foo.cam.net

  tasks:
  
    - name: Basic condition 
      win_shell: Get-Content -Path {{ hostspath }}
      register: hosts_info
      when: ansible_system == "Win32NT"

    - name: "Display valriable data"
      debug:
        msg: "{{ hosts_info }}"

    - name: Use a block
      block:
        - name: Fetch file to fail
          fetch:
            src: '{{ dontexist }}'
            dest: /tmp/
            flat: true
      when: ansible_system == "Win32NT"
      rescue:
        - name: "Please rescue me as I did not work"
          debug:
            msg: "ERROR: the block code did not work."