---
# ------------------------------------------------
# Camerons Ansible PlayBook 2
#
# Purpose: Variables in the different locations
#           1 Playbook
#           2 Host
#           3 Invetory
#           4 Template
#           5 From a File
# ------------------------------------------------
- name: Cam's playbook 2
  gather_facts: false
  hosts: all
  
  vars:
    var1PB: "Text from the PlayBook. Variable 1"
  
  vars_files:
    - ./files/cams_varaible.yml
  
  tasks:
    - name: "Variable 1 from Playbook itself"
      win_shell: echo "{{ var1PB }}"
    
    - name: "Variable 2 from Host"
      win_shell: echo "{{ var2Host }}"
    
    - name: "Variable 3 from Invetory"
      win_shell: echo "{{ var3Inv }}"
    
    - name: "Variable 4 from Template"
      win_shell: echo "{{ var4Temp }}"
      
    - name: "Variable 5 from a file"
      win_shell: echo "{{ var5file }}"
