---
# ------------------------------------------------
# Camerons Ansible PlayBook 3
#
# Purpose: Variables in the different locations
#           1 Playbook
#           2 Host
#           3 Invetory
#           4 Template
#           5 From a File
# ------------------------------------------------
- name: Cam's playbook 3
  gather_facts: false
  hosts: all
  
  vars:
    var1PB: "Text from the PlayBook. Variable 1"
  
  vars_files:
    - ./files/cams_varaible.yml
  
  tasks:
    - name: "Variable 1 from Playbook itself"
      debug: 
        msg: "{{ var1PB }}"
    
    - name: "Variable 2 from Host"
      debug: 
        msg: "{{ var2Host }}"
    
    - name: "Variable 3 from Invetory"
      debug: 
        msg: "{{ var3Inv }}"
      ignore_errors: true
    
    - name: "Variable 4 from Template"
      debug: 
        msg: "{{ var4Temp }}"
      
    - name: "Variable 5 from a file"
      debug: 
        msg: "{{ var5file }}"
